version: "2"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
#        - 7000:7000

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    hostname: localhost
    network_mode: host
    ports:
      - 3306:3306
    #    cap_add:
    #      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: 'Password'
      MYSQL_DATABASE: authenticationDB
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "YES"


  mongodb:
    image: mongo:latest
    container_name: mongo-container
    network_mode: host
    hostname: localhost
    ports:
      - 27017:27017

  neo4j:
    image: neo4j:4.2.3
    container_name: neo4j
    restart: always
    network_mode: host
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      NEO4J_AUTH: neo4j/password



#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
#    container_name: elasticsearch
#    environment:
#      - node.name=elasticsearch
#      - cluster.name=elasticsearch
#      - discovery.type=single-node
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ports:
#      - 9200:9200
#      - 9300:9300


  eureka-server:
    build: eureka-server/
    container_name: eureka-server
    restart: always
    network_mode: host
    hostname: localhost
    ports:
      - 8761:8761

  api-gateway:
    build: api-gateway/
    container_name: api-gateway
    depends_on:
      - eureka-server
    restart: always
    network_mode: "host"
    hostname: localhost
    ports:
      - 8080:8080

  application-register-service:
    build: application-register-service/
    container_name: application-register-service
    depends_on:
      - mongodb
      - eureka-server
    network_mode: "host"
    hostname: localhost
    restart: always
    ports:
      - 8098:8098

  authentication-service:
    build: authentication-service/
    container_name: authentication-service
    depends_on:
      - mysql
      - eureka-server
    network_mode: host
    hostname: localhost
    restart: always
    ports:
        - 8099:8099


  product-webapp:
    build: product-webapp/
    image: product-webapp
    restart: always
    container_name: product-webapp
    network_mode: host
    hostname: localhost
    ports:
      - 4200:4200

  trend-lab-service:
#    image: trendlabimage
    build: trend-lab-service/
    container_name:   trend-lab-service
    restart: always
    hostname: localhost
    network_mode: host
    depends_on:
      - mongodb
      - eureka-server
    ports:
      - 8086:8086

  chatroom-service:
#    image: chatroomimage
    build: chatroom-service/
    container_name: chatroom-service
    restart: always
    hostname: localhost
    network_mode: host
    depends_on:
      - mongodb
      - eureka-server
    ports:
      - 8089:8089

  email-service:
#    image: emailservice
    build: email-service/
    container_name: email-service
    restart: always
    hostname: localhost
    network_mode: host
    depends_on:
      - eureka-server
    ports:
      - 8085:8085

  assessment-service:
#    image: assessmentservice
    build: assessment-service/
    restart: always
    hostname: localhost
    network_mode: host
    depends_on:
      - mongodb
      - eureka-server
    ports:
      - 8081:8081

  post-service:
    image: postservice
    build: post-service/
    restart: always
    network_mode: host
    depends_on:
      - mongodb
      - eureka-server
    ports:
      - 9093:9093

  recommendation-service:
    image: recommendationservice
    build: recommendation-service/
    restart: always
    network_mode: host
    depends_on:
      - neo4j
      - eureka-server
    ports:
      - 8083:8083


  resources-service:
    build: resources-service/
    restart: always
    network_mode: host
    depends_on:
      - mongodb
      - eureka-server
    ports:
      - 8087:8087


